name: Backup Firestore2

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: un-colab-chat
  BUCKET: gs://backup-uncolab

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
